import pandas as pd

data = pd.read_csv("/home/nikola/6_analiza_otpornosti/grouped_mean_rcp_4_5.csv", delimiter =";", index_col=0)

variables_indexes = {"bbd_periodmean",
"cllfd_periodmean",
"codd_periodmean",
"cwd_periodmean",
"fg10_172_periodmean",
"fg10_extreme_periodmean",
"fg10_high_periodmean",
"fg10_low_periodmean",
"fg10_moderate_periodmean",
"fg10_pondered_periodmean",
"fg10_very_high_periodmean",
"fg10_ymax_periodmean",
"fi_max_periodmax",
"fwi_extreme_periodmean",
"fwi_high_periodmean",
"fwi_low_periodmean",
"fwi_max_periodmean",
"fwi_moderate_periodmean",
"fwi_very_high_periodmean",
"hi_extreme_periodmean",
"hi_high_periodmean",
"hi_low_periodmean",
"hi_max_periodmean",
"hi_moderate_periodmean",
"hi_pondered_periodmean",
"lfd_after_bbd_periodmean",
"llfi_periodmean",
"r95p_periodmean",
"spi3_dry_min_periodmean",
"spi3_extremely_dry_periodmean",
"spi3_extremely_wet_periodmean",
"spi3_mild_dry_periodmean",
"spi3_mild_wet_periodmean",
"spi3_moderately_dry_periodmean",
"spi3_moderately_wet_periodmean",
"spi3_normal_periodmean",
"spi3_pondered_dry_periodmean",
"spi3_severely_dry_periodmean",
"spi3_severely_wet_periodmean",
"su30_periodmean",
"tasmax_ymax_periodmean",
"tmin_after_bbd_periodmean",
"tn90p_summer_periodmean",
"tr_periodmean",
"tx90p_summer_periodmean",
"wildfire_orig_periodmean",
"heat_wave_orig_periodmean",
"river_flood_orig_periodmean",
"heavy_precipitation_orig_periodmean",
"severe_wind_orig_periodmean",
"drought_orig_periodmean",
"late_frost_orig_periodmean",
"extras_new_fake_periodmean"}